### ISSUE TITLE
/mnt/user/system/./locatefileinarray.sh: No such file or directory

### ISSUE THREAD

**Issue by dada051** [bexem/PlexOnDeckCache#4]
When I run the script, I have this error:
/mnt/user/system/./locatefileinarray.sh: No such file or directory
don't know where I can find this locatefileinarray.sh file.

**Comment by bexem** [comment]
Hello, my apologies, I should have uploaded that file as well! My bad! It is now up, you just need to have it in the same folder of the script (I will try to implement it on the same script soon). Don't forget to give it the permissions to run!

**Comment by bexem** [comment]
I have integrated the script to locate the file directly in the python script, so you should not get the error anymore.

**Comment by dada051** [comment]
Just saw the fix. Maybe we can use /mnt/user0/ directly instead of searching in /mnt/disk{09} ?

**Comment by bexem** [comment]
That sounds like a way better solution! I don't even have to iterate the whole thing making it more efficient. I like it, thank you! I was unaware of the functionality of this folder in unraid!
I have now updated the code!
